spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luoxin?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

  auto:
    openurl: true
  web:

#    googleexcute: C:\Program Files\Google\Chrome\Application\\chrome.exe
    edge: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

    loginurl: http://localhost:8080/doc.html

  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/

  redis:
    host: 192.168.15.131
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: 123456
    database: 0
  cache:
    redis:
      time-to-live: 1800000

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com/example/ims/entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      # Scan your controller package.
      packages-to-scan: com.foottime.receptiodesk.controller
